# k8s/csi-driver/controller-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: awesomefs-csi-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awesomefs-csi-controller
  template:
    metadata:
      labels:
        app: awesomefs-csi-controller
    spec:
      serviceAccountName: awsomefs-csi-sa
      containers:
        - name: csi-driver
          image: localhost/awsomefs/csi-awsomefs:latest
          imagePullPolicy: Never
          securityContext:
            privileged: true
          args:
            - "--endpoint=unix://csi/csi.sock"
            - "--mode=controller"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: mountpoint-dir
              mountPath: /mnt/awsomefs
              mountPropagation: "Bidirectional"

        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v3.6.0
          args:
            - "--csi-address=/csi/csi.sock"
            # - "--leader-election=true"
            - "--v=5"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi

      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/awsomefs.csi.driver
            type: DirectoryOrCreate
        - name: mountpoint-dir
          hostPath:
            path: /mnt/awsomefs
            type: Directory