apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: awsomefs.csi.driver
spec:
  attachRequired: false
  podInfoOnMount: true
  volumeLifecycleModes:
    - Persistent
  fsGroupPolicy: File
