# service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: awsomefs-csi-sa
  namespace: default
---
# role granting access to resources CSI sidecars need
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awsomefs-csi-role
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims", "persistentvolumes", "nodes"]
    verbs: ["get", "list", "watch", "create","delete"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses", "csinodes", "volumeattachments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["csi.storage.k8s.io"]
    resources: ["csidrivers", "csinodeinfos"]
    verbs: ["get", "list", "watch"]
---
# bind role to service account
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: awsomefs-csi-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: awsomefs-csi-role
subjects:
  - kind: ServiceAccount
    name: awsomefs-csi-sa
    namespace: default
