apiVersion: v1
kind: Pod
metadata:
  name: awesomefs-test-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "echo Hello AwesomeFS > /data/hello.txt && sleep 3600"]
      volumeMounts:
        - mountPath: /data
          name: awesomefs-vol
  volumes:
    - name: awesomefs-vol
      persistentVolumeClaim:
        claimName: test-awesomefs-pvc  # replace with your actual PVC name
