kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: devfs-cluster

# Define the Kubernetes version
# kubernetesVersion: v1.26.0

# Specify the number of nodes (control-plane and worker nodes)
nodes:
  - role: control-plane
    image: kindest/node:v1.26.0
  - role: worker
    image: kindest/node:v1.26.0
    extraMounts:
      - hostPath: /tmp/loopback-device
        containerPath: /dev/sdb
  - role: worker
    image: kindest/node:v1.26.0
    extraMounts:
      - hostPath: /tmp/loopback-device
        containerPath: /dev/sdb
  - role: worker
    image: kindest/node:v1.26.0
    extraMounts:
      - hostPath: /tmp/loopback-device
        containerPath: /dev/sdb
